# /etc/dnsmasq.d/ap.conf  
interface=wlan0
bind-interfaces

domain-needed
bogus-priv

dhcp-range=192.168.4.50,192.168.4.150,255.255.255.0,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
log-dhcp

dhcp-option=114,http://192.168.4.1/

# Android captive detection
address=/connectivitycheck.gstatic.com/192.168.4.1
address=/clients3.google.com/192.168.4.1
address=/connectivitycheck.android.com/192.168.4.1

# Apple captive detection
address=/captive.apple.com/192.168.4.1
address=/www.apple.com/192.168.4.1

# Windows captive detection
address=/www.msftconnecttest.com/192.168.4.1
address=/msftconnecttest.com/192.168.4.1
address=/www.msftncsi.com/192.168.4.1
address=/msftncsi.com/192.168.4.1

# Firefox captive detection
address=/detectportal.firefox.com/192.168.4.1
